kind: Deployment
apiVersion: v1
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 3
  selector:
    matchlabels:
      app: nginx
  template:
     metadata:
        labels:
          app: nginx
     spec:
       containers:
    - name: c00
      image: nginx
      command: ["/bin/bash", "-c", "while true; do echo Hello-Risav; sleep 5 ; done"]
      

